spring.application.name=spring-boot-mybatisplus
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/mybatis-plus-test?useUnic
ode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverT
imezone=UTC
spring.datasource.username=root
spring.datasource.password=maxu20040310