spring:
  datasource:
    # ????????mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ??????mysql???????????
    url: jdbc:mysql://localhost:3306/springsecurity?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: maxu20040310

  spring:
    security:
      user:
        name: admin
        password: 123
        roles: USER, ADMIN



  jpa:
    show-sql: true  # ??SQL??
    open-in-view: true
    hibernate:
      ddl-auto: update
      # ????create, create-drop, update, validate, none
      #   create??????????????
      #   create-drop??????????????
      #   update??????????????????
      #   validate????????????
      #   none???????
    defer-datasource-initialization: true # ?????????????????????????????import.sql????Hibernate????DDL??????????????
    properties:
      hibernate:
        format_sql: true  # ????SQL??